### ISSUE TITLE
Wrong namespace  namespace Valitor\Api\Payments;

### ISSUE THREAD

**Issue by maxvovk** [AltaPay/Magento2Community#1]
in file Magento2Community/Api/Payments/RefundCapturedReservation.php
 --> `namespace Valitor\Api\Payments;` must be changed to `namespace SDM\Valitor\Api\Payments;`

**Comment by AJenbo** [comment]
This has been solved: https://github.com/AltaPay/Magento2Community/commit/e3be013c742bedb2005fef38022bcebeb55c33cd#diff-2a091eb9506716e68a8d12a76eb7271fR24
